package webhook

import "strings"

// Small subset of Slack emoji shortcodes, enough for common reactions used
// as icon_emoji values. Unknown shortcodes are kept as-is.
var emojiShortcodes = map[string]string{
	"+1":                   "👍",
	"-1":                   "👎",
	"100":                  "💯",
	"airplane":             "✈️",
	"alarm_clock":          "⏰",
	"angry":                "😠",
	"art":                  "🎨",
	"baby":                 "👶",
	"bangbang":             "‼️",
	"bell":                 "🔔",
	"bug":                  "🐛",
	"bulb":                 "💡",
	"cake":                 "🍰",
	"clap":                 "👏",
	"coffee":               "☕",
	"computer":             "💻",
	"crown":                "👑",
	"cry":                  "😢",
	"dancer":               "💃",
	"dart":                 "🎯",
	"dash":                 "💨",
	"eyes":                 "👀",
	"fire":                 "🔥",
	"gift":                 "🎁",
	"ghost":                "👻",
	"globe_with_meridians": "🌐",
	"green_heart":          "💚",
	"heart":                "❤️",
	"heart_eyes":           "😍",
	"heavy_check_mark":     "✔️",
	"heavy_plus_sign":      "➕",
	"heavy_minus_sign":     "➖",
	"hourglass":            "⌛",
	"info":                 "ℹ️",
	"joy":                  "😂",
	"key":                  "🔑",
	"laughing":             "😆",
	"link":                 "🔗",
	"lock":                 "🔒",
	"mag":                  "🔍",
	"mega":                 "📣",
	"memory":               "🧠",
	"metal":                "🤘",
	"moon":                 "🌙",
	"muscle":               "💪",
	"no_entry":             "⛔",
	"ok_hand":              "👌",
	"open_hands":           "👐",
	"package":              "📦",
	"pencil":               "✏️",
	"pin":                  "📌",
	"point_right":          "👉",
	"pray":                 "🙏",
	"punch":                "👊",
	"question":             "❓",
	"rage":                 "😡",
	"raised_hands":         "🙌",
	"recycle":              "♻️",
	"relaxed":              "☺️",
	"rocket":               "🚀",
	"santa":                "🎅",
	"scream":               "😱",
	"shirt":                "👕",
	"skull":                "💀",
	"sleeping":             "😴",
	"smile":                "😄",
	"smiley":               "😃",
	"sob":                  "😭",
	"sparkles":             "✨",
	"sunglasses":           "😎",
	"sunflower":            "🌻",
	"sunny":                "☀️",
	"sweat_smile":          "😅",
	"tada":                 "🎉",
	"thumbsdown":           "👎",
	"thumbsup":             "👍",
	"warning":              "⚠️",
	"waving_hand":          "👋",
	"wink":                 "😉",
	"x":                    "❌",
	"zap":                  "⚡",
}

// LookupEmoji resolves a `:shortcode:` (with or without colons) to a unicode
// emoji. Unknown shortcodes are returned unchanged.
func LookupEmoji(shortcode string) string {
	trimmed := strings.Trim(strings.TrimSpace(shortcode), ":")
	if emoji, ok := emojiShortcodes[trimmed]; ok {
		return emoji
	}
	return shortcode
}
